### ISSUE TITLE
Election model

### ISSUE THREAD

**Issue by snbhattacharjya** [snbhattacharjya/ppms#13]
This is the main backbone model for creating multiple election context in parallel. In future this may help even running central and state election simultaneously.

**Comment by abusalam** [comment]
What should be the contents?

**Comment by snbhattacharjya** [comment]
- Name
- Year
- State

**Comment by abusalam** [comment]
Type like Municipality, Panchayat, Assembly, Parliament should also be there as some logics vary depending on this.

**Comment by snbhattacharjya** [comment]
Panchayat, Municipality or Assemblies are all choices of constituencies. For implementing logic of forming Polling Parties in different election context controller based approach would be better. This can make the model clean.
