### ISSUE TITLE
Constituency

### ISSUE THREAD

**Issue by snbhattacharjya** [snbhattacharjya/ppms#16]
Our main problem with elections was primarily many solutions for single problem domain. This made us think in silos towards approaching election related software stacks. This model solves the problem of making the system election agnostic. Whatever maybe the context of election; Parliament, Assembly, Panchayat or Municipality there will be a single solution towards them.

**Comment by snbhattacharjya** [comment]
A constituency is either a Assembly, block or municipality that is related to a election phase under a election model.

**Comment by abusalam** [comment]
Please elaborate with examples and how you have planned the solution. Panchayat election has 3tiers where  others have one or two.

**Comment by snbhattacharjya** [comment]
We are here solving the problem of managing Election officers both polling or counting. Be it any tier election the logic of forming polling parties mostly remain same. The composition of parties i.e. number of officers in a party may differ but then again it is a different problem area that can be separately addressed.
