### ISSUE TITLE
Create Employee Model

### ISSUE THREAD

**Issue by snbhattacharjya** [snbhattacharjya/ppms#2]
This will be a basic Employee Model, only covering those attributes that will be necessary for initial management of categorizing them into polling officers. Later on the model might have one-to-one relationship with Epic, Contact, Bank Models to capture the respective domains.

**Comment by snbhattacharjya** [comment]
@abusalam Suggest about the PayLevel for Employees of both Central and state Govt. I think it should be separate model having on-many relation with employees. Structure may be like this:

- id
- name
- service_type //Central or State
- time_stamps

**Comment by abusalam** [comment]
First thing we should consider that how we re going to use that data? If we need to query it through database then we should keep them in employees table otherwise we should go for different table if we are going to get it and use by classes.

**Comment by snbhattacharjya** [comment]
We can have situation of using that data to categorize employees and also the pay levels may also be used to get group by reports. In that case we can keep them as a separate table.

**Comment by abusalam** [comment]
We need to decide on the workflow we are going to opt for categorisation. It may be query based (a single query will update multiple records) or procedural where classes will do the job and update the records one by one. I prefer the later one.

**Comment by abusalam** [comment]
Implementation of seeders are required

**Comment by snbhattacharjya** [comment]
I am planning to build the seeders by District to check the integration as well as functionality.
